### ISSUE TITLE
[Account] 계좌 Constructor 추가

### ISSUE THREAD

**Issue by kyunghwaisdev** [Choi-Won-Jun/bankServiceProject#5]
현재 : 계좌 생성 부분 Constructor 부분이 빠져있음
수정 : repository에서 만들어 준 계좌번호 + 고객이 입력한 이름 + Balance 0원 --> 계좌 생성 해두기

* 추후에 repository에서 알아서 가져감

**Comment by J-Jaeh** [comment]
Account.java여기 맨 윗 줄에 package org.example;  요거 깃 허브 저장소에 등록 해야 할 거 같아요

**Comment by kyunghwaisdev** [comment]
Constructor 추가 완료
