### ISSUE TITLE
[AccountRepository] 계좌 수정/삭제 시나리오

### ISSUE THREAD

**Issue by kyunghwaisdev** [Choi-Won-Jun/bankServiceProject#6]
참고 ! 요구사항에 기재되어있는 수정/삭제의 의미 : 계좌중단/거래재개/계좌삭제 와 같은 의미

- [x] <Issue1>

- 현재 : 삭제(removeAccount) 메소드에서 ownerName조회하여 계좌 삭제하게 되어있는데, 그렇게 되면 중복 발생? 등의 문제가 생김 
- 수정 : ownerName이 아니라 accountNum으로 조회하여 계좌 삭제하는 것으로 수정

- [ ] <Issue2>

- 현재 : 계좌 수정(거래 중지, 거래 재개 등)의 case가 빠져있음
- 수정 : 논의하여 필요하다면, 수정 시 시나리오 및 메소드 등 추가 필요
- ex."해당 계좌는 거래가 중지되었습니다." "거래 재개를 요청 하시겠습니까 ? 1.네 2.아니요" .... 이런식으로

**Comment by J-Jaeh** [comment]
대박 체크리스트 신기해요

**Comment by kyunghwaisdev** [comment]
그죠 ?ㅋㅋㅋㅋ 별거 아닌데 뭔가 간지쓰....... 있길래 만들어 봤어요 !

**Comment by kyunghwaisdev** [comment]
수정 기능은 구현하지 않는 것으로 결론
